version: "3.9"
services:
  test:
    image: starknetfoundation/starknet-dev:2.8.4
    volumes:
      - .:/app
    command: scarb test
  deploy:
    image: starknetfoundation/starknet-dev:2.8.4
    volumes:
      - .:/app
    command: npm run deploy
